### PR TITLE
Handle non root server

### PR DESCRIPTION
**Pull request by jsoref**
I made the "mistake" of configuring http://example.com/dnsui/ instead of http://dnsui.example.com/ as a result, the app didn't work.

### CODE REVIEW

**Comment by thomas-pike** [comment]
Can you give some more details about how you have configured your instance please? Specifically:

* Apache or Nginx?
* How have you configured the web server to serve it under a subdirectory?

I have a slightly different patch in mind, but I want to make sure that it will work for your setup.

**Comment by jsoref** [comment]
Apache.
Yes, Apache is configured to serve it under a subdirectory.

**Comment by thomas-pike** [comment]
Right, but how? Using an `Alias` directive? Can you share part of the configuration? (And also how you have `baseurl` defined in the DNSUI config.

Thanks in advance for any information you can provide.

**Comment by jsoref** [comment]
```
<VirtualHost *:443>
        DocumentRoot /var/www/html

        Alias "/dnsui" "/var/www/dns-ui/public_html"
        <Directory /var/www/dns-ui/public_html>
                DirectoryIndex init.php
                FallbackResource /dnsui/init.php
                AuthName "DNS UI"
                AuthType Basic
                AuthBasicProvider ldap
                AuthLDAPURL ldap://ldap/ou=People,dc=example,dc=com?uid
                Require valid-user
                Order allow,deny
                Allow from all
        </Directory>
</VirtualHost>
```

**Comment by jsoref** [comment]
```
; Do not include a trailing / in the baseurl
baseurl = https://www.example.com/dnsui
```

**Comment by jsoref** [comment]
@thomas-pike is there anything else you need?

**Comment by thomas-pike** [comment]
Closing this as #104 was merged instead. Regardless, thank you for your contributions.

**Pull request closed without merging**
